Repository softeerbootcamp-2nd/H6-CaArt, pull requests merged in 2023-08, with the labels that each got.

#15 [FE] feat: 툴팁 컴포넌트 제작
  frontend/.prettierrc.js
  frontend/.yarn/sdks/eslint/bin/eslint.js
  frontend/.yarn/sdks/eslint/lib/api.js
  frontend/.yarn/sdks/eslint/package.json
  frontend/package-lock.json
  frontend/public/images/tooltip_icon.svg
  frontend/src/App.tsx
  frontend/src/components/common/ToolTip.tsx
  frontend/src/style/index.css
Labels: 기능개발 👨‍💻

#19 [AOS] design: 차량 색깔 선택 페이지 레이아웃 요소 배치 #16
  Android/app/src/main/res/layout/fragment_car_color_choice.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/styles_textView.xml
Labels: 디자인 🖌

#25 [AOS] desigin: 리소스 추가
  Android/app/src/main/res/drawable/ic_rotate_56.xml
  Android/app/src/main/res/drawable/img_car_background.xml
  Android/app/src/main/res/drawable/img_car_background_with_circle.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
Labels: 디자인 🖌

#29 [AOS] design: 차량 색깔 선택 페이지 레이아웃 요소 배치 #26
  Android/app/src/main/res/drawable/img_car_exterior.png
  Android/app/src/main/res/drawable/img_car_interior.png
  Android/app/src/main/res/layout/fragment_car_color_choice.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/styles_textView.xml
Labels: 디자인 🖌

#24 [FE] feat: 태그 컴포넌트 제작
  frontend/src/components/common/tag.tsx
  frontend/src/components/common/tagList.tsx
  frontend/src/static/font/HyundaiSansHeadKRBold.woff
  frontend/src/static/font/HyundaiSansHeadKRBold.woff2
  frontend/src/static/font/HyundaiSansHeadKRMedium.woff
  frontend/src/static/font/HyundaiSansHeadKRMedium.woff2
  frontend/src/static/font/HyundaiSansHeadOffice-Bold.woff
  frontend/src/static/font/HyundaiSansHeadOffice-Bold.woff2
  frontend/src/static/font/HyundaiSansHeadOffice-Medium.woff
  frontend/src/static/font/HyundaiSansHeadOffice-Medium.woff2
  frontend/src/static/font/HyundaiSansTextKRBold.woff
  frontend/src/static/font/HyundaiSansTextKRBold.woff2
  frontend/src/static/font/HyundaiSansTextKRMedium.woff
  frontend/src/static/font/HyundaiSansTextKRMedium.woff2
  frontend/src/static/font/HyundaiSansTextKRRegular.woff
  frontend/src/static/font/HyundaiSansTextKRRegular.woff2
  frontend/src/static/font/HyundaiSansTextOffice-Bold.woff
  frontend/src/static/font/HyundaiSansTextOffice-Bold.woff2
  frontend/src/static/font/HyundaiSansTextOffice-Medium.woff
  frontend/src/static/font/HyundaiSansTextOffice-Medium.woff2
  frontend/src/static/font/HyundaiSansTextOffice-Regular.woff
  frontend/src/static/font/HyundaiSansTextOffice-Regular.woff2
  frontend/src/style/font.css
Labels: 기능개발 👨‍💻

#30 [AOS] design: 세부사항 인디케이터 구현 및 기타 오류 수정
  Android/app/build.gradle
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/TextViewBindingAdapter.kt
  Android/app/src/main/res/layout/layout_detail_indicator.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/styles_textView.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#31 [FE] feat: 로고 컴포넌트 제작
  frontend/public/images/dropdown_icon_default.svg
  frontend/public/images/dropdown_icon_home.svg
  frontend/public/images/hyundai_logo_default.svg
  frontend/public/images/hyundai_logo_home.svg
  frontend/src/components/common/Logo.tsx
Labels: 기능개발 👨‍💻

#27 [FE] feat: 사각 버튼 컴포넌트 제작
  frontend/src/App.tsx
  frontend/src/components/common/SquareButton.tsx
  frontend/src/style/index.css
Labels: 기능개발 👨‍💻

#34 [FE] feat: 원형 컴포넌트 제작
  frontend/public/images/blue-lg-check-icon.svg
  frontend/public/images/blue-sm-check-icon.svg
  frontend/public/images/grey-lg-check-icon.svg
  frontend/public/images/white-lg-check-icon.svg
  frontend/src/App.tsx
  frontend/src/components/common/CheckButton.tsx
  frontend/src/components/common/CircularButton.tsx
Labels: 기능개발 👨‍💻

#41 [FE] fix: 로고 컴포넌트 오류 수정
  frontend/src/components/common/Logo.tsx
  frontend/src/components/common/tagList.tsx
Labels: 수정 🛠

#42 [BE] feat: 프로젝트 초기 세팅
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/softeer/caart/domain/Image.java
  backend/src/main/java/com/softeer/caart/domain/bodytype/BodyType.java
  backend/src/main/java/com/softeer/caart/domain/color/Color.java
  backend/src/main/java/com/softeer/caart/domain/engine/CarEngine.java
  backend/src/main/java/com/softeer/caart/domain/model/AvailableOption.java
  backend/src/main/java/com/softeer/caart/domain/model/Model.java
  backend/src/main/java/com/softeer/caart/domain/option/Badge.java
  backend/src/main/java/com/softeer/caart/domain/option/CarOption.java
  backend/src/main/java/com/softeer/caart/domain/option/ChildCarOption.java
  backend/src/main/java/com/softeer/caart/domain/option/OptionTag.java
  backend/src/main/java/com/softeer/caart/domain/tag/Tag.java
  backend/src/main/java/com/softeer/caart/domain/tag/TagType.java
  backend/src/main/java/com/softeer/caart/domain/trim/AvailableColor.java
  backend/src/main/java/com/softeer/caart/domain/trim/Trim.java
  backend/src/main/java/com/softeer/caart/domain/wd/WheelDrive.java
Labels: 기능개발 👨‍💻

#49 [BE] feat: 예외 처리 및 응답 형태 세팅
  backend/src/main/java/com/softeer/caart/CaArtServerApplication.java
  backend/src/main/java/com/softeer/caart/global/ResultCode.java
  backend/src/main/java/com/softeer/caart/global/exception/BusinessException.java
  backend/src/main/java/com/softeer/caart/global/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/softeer/caart/global/response/DataResponseDto.java
  backend/src/main/java/com/softeer/caart/global/response/ErrorResponseDto.java
  backend/src/main/java/com/softeer/caart/global/response/ResponseDto.java
  backend/src/test/java/com/softeer/caart/CaArtServerApplicationTests.java
Labels: 기능개발 👨‍💻

#54 [FE] feat: 프론트엔드 페이지 구조 설계 및 세팅
  frontend/.prettierrc.js
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/components/homePage/homePage.txt
  frontend/src/components/recommendPage/recommendPage.txt
  frontend/src/components/resultPage/resultPage.txt
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/colorEstimationPage.txt
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionEstimationPage.txt
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/trimEstimationPage.txt
  frontend/src/components/vehicleEstimationPage/vehicleEstimationPage.txt
  frontend/src/pages/homePage/HomePage.tsx
  frontend/src/pages/recommendPage/RecommendPage.tsx
  frontend/src/pages/resultPage/ResultPage.tsx
  frontend/src/pages/vehicleEstimationPage/ColorEstimationPage.tsx
  frontend/src/pages/vehicleEstimationPage/OptionEstimationPage.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
  frontend/src/pages/vehicleEstimationPage/VehicleEstimationPage.tsx
  frontend/src/style/reset.css
  frontend/src/util/Context.tsx
Labels: 기능개발 👨‍💻, 설계 📐

#50 [AOS] feat: 버튼 두개 다이얼로그 구현
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/TextViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dialogs/TwoButtonsDialog.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/interfaces/OnButtonClickListener.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/HomeFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/utils/UnitConverter.kt
  Android/app/src/main/res/drawable/shape_dialog_text_background.xml
  Android/app/src/main/res/drawable/shape_round_background_12.xml
  Android/app/src/main/res/layout/dialog_two_buttons.xml
  Android/app/src/main/res/layout/layout_detail_indicator.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/dimens.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/styles_button.xml
  Android/app/src/main/res/values/styles_textView.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#73 [FE] feat: 옵션 카드 컴포넌트 구현
  frontend/public/images/rightArrow_icon_blue.svg
  frontend/src/components/common/Logo.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/optionCard.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/optionCardGuide.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/optionCardTag.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionEstimationPage.txt
  frontend/src/style/index.css
  frontend/src/util/priceToString.ts
  frontend/src/util/truncateString.ts
Labels: 기능개발 👨‍💻

#52 [AOS] feat: 커스텀 바텀 시트 기능부 구현 #51
  Android/app/src/main/java/org/softeer_2nd/caArt/CustomBottomSheet.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ItemTestData.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/RecyclerAdapters/OptionSelectionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/BottomSheetBindingAdapter.kt
Labels: 기능개발 👨‍💻

#53 [AOS] design: 커스텀 바텀 시트 디자인부 구현 및 오류 수정
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/TextViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/ToolBarBindingAdapter.kt
  Android/app/src/main/res/drawable/drop_shadow.xml
  Android/app/src/main/res/drawable/ic_home_indicator.xml
  Android/app/src/main/res/drawable/ic_line.xml
  Android/app/src/main/res/drawable/shape_bottom_sheet_round.xml
  Android/app/src/main/res/layout/fragment_car_color_choice.xml
  Android/app/src/main/res/layout/item_option_select.xml
  Android/app/src/main/res/layout/layout_bottom_sheet_base.xml
  Android/app/src/main/res/layout/layout_bottom_sheet_down.xml
  Android/app/src/main/res/layout/layout_bottom_sheet_up.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/styles_textView.xml
Labels: 버그 🪲, 디자인 🖌

#74 [FE] feat: 레이아웃 배치 및 컨테이너, 버튼 구현
  frontend/public/images/check_circle_blue_bold.svg
  frontend/public/images/check_circle_grey_bold.svg
  frontend/public/images/question_icon.svg
  frontend/src/components/common/Header.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWButton.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/trimEstimationPage.txt
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
  frontend/src/util/Context.tsx
Labels: 기능개발 👨‍💻

#77 [AOS] refactor: 바텀 시트 코드 리팩토링
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/org/softeer_2nd/caArt/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/RecyclerAdapters/OptionSelectionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ToolBarBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/TextViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/factorys/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/models/OptionSelectionDummyItem.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CustomBottomSheet.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/MainActivity.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodels/ToolBarViewModel.kt
  Android/app/src/main/res/drawable/drop_shadow.xml
  Android/app/src/main/res/layout/activity_main.xml
  Android/app/src/main/res/layout/dialog_two_buttons.xml
  Android/app/src/main/res/layout/fragment_car_color_choice.xml
  Android/app/src/main/res/layout/item_option_select.xml
  Android/app/src/main/res/layout/layout_bottom_sheet_base.xml
  Android/app/src/main/res/layout/layout_bottom_sheet_down.xml
  Android/app/src/main/res/layout/layout_bottom_sheet_up.xml
  Android/app/src/main/res/values/colors.xml
Labels: 리팩토링 🔧, 디자인 🖌

#80 [AOS] feat: 각 화면에 맞는 바텀 시트를 보여주기
  Android/app/src/main/java/org/softeer_2nd/caArt/BottomSheetMode.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/BottomSheetBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/factorys/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CarColorChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CustomBottomSheet.kt
  Android/app/src/main/res/layout/fragment_car_color_choice.xml
  Android/app/src/main/res/layout/layout_bottom_sheet_down.xml
Labels: 기능개발 👨‍💻, 수정 🛠, 디자인 🖌

#86 [AOS] feat: 내부 색상, 외부 색상 라싸이클러 뷰 아이템 구현
  Android/app/src/main/java/org/softeer_2nd/caArt/RecyclerAdapters/ColorOptionSelectionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/RecyclerAdapters/OptionSelectionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/factorys/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/models/OptionColorDummyItem.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CarColorChoiceFragment.kt
  Android/app/src/main/res/drawable/ic_check_circle_24.xml
  Android/app/src/main/res/drawable/img_option_color1.png
  Android/app/src/main/res/drawable/img_option_color2.png
  Android/app/src/main/res/drawable/img_option_color3.png
  Android/app/src/main/res/drawable/shape_top_tag_round.xml
  Android/app/src/main/res/layout/item_color_select.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#83 [FE] design: 버튼 컴포넌트 수정 및 이미지 배치
  frontend/public/images/car.png
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWButton.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCarImage.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimContainer.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
Labels: 수정 🛠, 디자인 🖌

#88 [AOS] feat: 다이얼로그에 빌더 패턴 적용
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/TextViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/ViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dialogs/CaArtDialog.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dialogs/TwoButtonsDialog.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/interfaces/OnButtonClickListener.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/interfaces/OnDialogClickListener.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/HomeFragment.kt
  Android/app/src/main/res/drawable/shape_dialog_text_background.xml
  Android/app/src/main/res/layout/dialog_caart.xml
  Android/app/src/main/res/layout/dialog_two_buttons.xml
  Android/app/src/main/res/layout/fragment_home.xml
  Android/app/src/main/res/values/dimens.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#82 [BE] feat: Swagger 연동
  backend/build.gradle
  backend/src/main/java/com/softeer/caart/domain/model/controller/ModelController.java
  backend/src/main/java/com/softeer/caart/global/config/SwaggerConfig.java
Labels: 기능개발 👨‍💻

#91 [BE] chore: CI/CD 파이프라인 구축
  .github/workflows/be-build-test.yml
  .github/workflows/be-deploy.yml
Labels: 기능개발 👨‍💻

#99 [AOS] refactor: 바인딩 어댑터 선언 방식 변경
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/CarColorChoiceBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/ToolBarBindingAdapter.kt
Labels: 리팩토링 🔧

#97 [FE] feat: 옵션 탭바 구현
  frontend/public/images/category_icon_all.svg
  frontend/public/images/category_icon_cold-hot.svg
  frontend/public/images/category_icon_convenience.svg
  frontend/public/images/category_icon_driving-safety.svg
  frontend/public/images/category_icon_main.svg
  frontend/public/images/category_icon_parking.svg
  frontend/public/images/category_icon_performance.svg
  frontend/public/images/category_icon_style.svg
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/navBar.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/navBarLower.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/navBarUpper.tsx
  frontend/src/style/reset.css
Labels: 기능개발 👨‍💻

#96 [FE] feat: 고르기 어렵다면? 클릭시 나오는 모달 구현
  frontend/public/images/engine2_2.svg
  frontend/public/images/x_icon.svg
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWGuideModal.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
  frontend/src/style/index.css
Labels: 기능개발 👨‍💻

#95 [BE] feat: 차량 구성 정보 조회 API 개발
  backend/src/main/java/com/softeer/caart/domain/Image.java
  backend/src/main/java/com/softeer/caart/domain/bodytype/BodyType.java
  backend/src/main/java/com/softeer/caart/domain/composition/bodyType/BodyType.java
  backend/src/main/java/com/softeer/caart/domain/composition/bodyType/dto/BodyTypeResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/controller/CompositionController.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/CompositionResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/engine/CarEngine.java
  backend/src/main/java/com/softeer/caart/domain/composition/engine/dto/CarEngineResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/repository/BodyTypeRepository.java
  backend/src/main/java/com/softeer/caart/domain/composition/repository/CarEngineRepository.java
  backend/src/main/java/com/softeer/caart/domain/composition/repository/WheelDriveRepository.java
  backend/src/main/java/com/softeer/caart/domain/composition/service/CompositionService.java
  backend/src/main/java/com/softeer/caart/domain/composition/wd/WheelDrive.java
  backend/src/main/java/com/softeer/caart/domain/composition/wd/dto/WheelDriveResponse.java
  backend/src/main/java/com/softeer/caart/domain/engine/CarEngine.java
  backend/src/main/java/com/softeer/caart/domain/model/AvailableOption.java
  backend/src/main/java/com/softeer/caart/domain/model/Model.java
  backend/src/main/java/com/softeer/caart/domain/model/controller/ModelController.java
  backend/src/main/java/com/softeer/caart/domain/option/CarOption.java
  backend/src/main/java/com/softeer/caart/domain/option/ChildCarOption.java
  backend/src/main/java/com/softeer/caart/domain/option/OptionTag.java
  backend/src/main/java/com/softeer/caart/domain/tag/TagType.java
  backend/src/main/java/com/softeer/caart/domain/trim/AvailableColor.java
  backend/src/main/java/com/softeer/caart/domain/trim/Trim.java
  backend/src/main/java/com/softeer/caart/domain/wd/WheelDrive.java
  backend/src/test/java/com/softeer/caart/domain/ImageTest.java
  backend/src/test/java/com/softeer/caart/domain/common/ServiceTest.java
  backend/src/test/java/com/softeer/caart/domain/composition/service/CompositionServiceTest.java
Labels: 기능개발 👨‍💻

#102 [AOS] feat: 확장뷰 구현 + 다이얼로그 피드백 반영
  Android/app/src/main/java/org/softeer_2nd/caArt/dialogs/CaArtDialog.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/HomeFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/ExpandableView.kt
  Android/app/src/main/res/layout/fragment_home.xml
  Android/app/src/main/res/values/attrs.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#105 [FE] feat: 추가 옵션 리스트 레이아웃 구현
  frontend/public/images/leftArrow_icon_basic.svg
  frontend/public/images/rightArrow_icon_basic.svg
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/optionCardListAdditionalAll.tsx
Labels: 기능개발 👨‍💻

#106 [FE] feat: 비교하기 버튼 클릭시 나오는 모달 구현 #93
  frontend/public/images/car/calligraphy.svg
  frontend/public/images/car/exclusive.svg
  frontend/public/images/car/leBlanc.svg
  frontend/public/images/car/prestige.svg
  frontend/public/images/carComponent/cluster.svg
  frontend/public/images/carComponent/navigation.svg
  frontend/public/images/carComponent/sit.svg
  frontend/public/images/carComponent/wheel.svg
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/CompareModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimContainer.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
Labels: 기능개발 👨‍💻

#111 [FE] fix: 헤더 컴포넌트 개선 및 리팩토링
  frontend/src/components/common/Header.tsx
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/header/HeaderDetail.tsx
  frontend/src/components/common/header/HeaderMain.tsx
  frontend/src/components/common/header/HeaderProgressBar.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
  frontend/src/util/Context.tsx
Labels: 리팩토링 🔧, 수정 🛠, 디자인 🖌

#113 [FE] feat: 기본옵션 모달 구현
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/OptionExplainModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/OuterColorContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimContainer.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
Labels: 기능개발 👨‍💻

#115 [BE] deploy: CI/CD 파이프라인 구축
  .github/workflows/backend-deploy.yml
Labels: 기능개발 👨‍💻

#108 [BE] test: JaCoCo 세팅
  .github/workflows/backend-test.yml
  .github/workflows/be-build-test.yml
  backend/build.gradle
  backend/src/test/java/com/softeer/caart/CaArtServerApplicationTests.java
Labels: 기능개발 👨‍💻

#120 [Fe] feat: 트림 페이지 전체 디자인 수정
  frontend/src/components/common/ToolTip.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/CompareModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWButton.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWGuideModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/OptionExplainModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimContainer.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
Labels: 기능개발 👨‍💻

#119 [FE] remove: 파일 삭제
  frontend/src/components/common/tag.tsx
  frontend/src/components/common/tagList.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/navBar.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/navBarLower.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/navBarUpper.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/optionCard.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/optionCardGuide.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/optionCardTag.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/optionCardListAdditionalAll.tsx
Labels: 수정 🛠

#117 [AOS] feat : 색상 선택 페이지 확장뷰, 팝업 메세지
  Android/app/src/main/java/org/softeer_2nd/caArt/factorys/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/interfaces/OnOtherColorItemClickListener.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/models/OptionChangePopUpDummyItem.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/recyclerAdapters/BottomSheetCurrentOptionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/recyclerAdapters/ColorOptionSelectionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/recyclerAdapters/OptionChangePopupAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CarColorChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CustomBottomSheet.kt
  Android/app/src/main/res/layout/fragment_car_color_choice.xml
  Android/app/src/main/res/layout/item_color_select.xml
  Android/app/src/main/res/layout/item_option_change_popup.xml
  Android/app/src/main/res/layout/layout_change_popup.xml
  Android/app/src/main/res/layout/layout_other_color_option.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#128 [BE] fix: test 워크플로 실행 시 DataSource 부재로 오류 발생
  .github/workflows/backend-test.yml
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/navBar.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/optionCardTag.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/optionCardListAdditionalAll.tsx
Labels: 수정 🛠

#127 [Fe] feat: 모달 스크롤시 반응 변경
  frontend/src/components/common/ToolTip.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimContainer.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
Labels: 기능개발 👨‍💻

#125 [FE] feat: 옵션 설명 모달 구현
  frontend/public/images/x_icon_basic.svg
  frontend/src/components/common/Tag.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModal.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModalDetail.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModalTitle.tsx
  frontend/src/style/index.css
Labels: 기능개발 👨‍💻

#124 [BE] feat: 트림 정보 조회 API 개발
  backend/src/main/java/com/softeer/caart/domain/color/Color.java
  backend/src/main/java/com/softeer/caart/domain/color/dto/ColorResponse.java
  backend/src/main/java/com/softeer/caart/domain/color/entity/Color.java
  backend/src/main/java/com/softeer/caart/domain/composition/controller/CompositionController.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/BodyTypeResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/CarEngineResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/CompositionResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/WheelDriveResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/entity/BodyType.java
  backend/src/main/java/com/softeer/caart/domain/composition/entity/CarEngine.java
  backend/src/main/java/com/softeer/caart/domain/composition/entity/WheelDrive.java
  backend/src/main/java/com/softeer/caart/domain/composition/repository/BodyTypeRepository.java
  backend/src/main/java/com/softeer/caart/domain/composition/repository/CarEngineRepository.java
  backend/src/main/java/com/softeer/caart/domain/composition/repository/WheelDriveRepository.java
  backend/src/main/java/com/softeer/caart/domain/composition/service/CompositionService.java
  backend/src/main/java/com/softeer/caart/domain/model/AvailableOption.java
  backend/src/main/java/com/softeer/caart/domain/model/Model.java
  backend/src/main/java/com/softeer/caart/domain/option/Badge.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/Badge.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/CarOption.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/ChildCarOption.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/OptionTag.java
  backend/src/main/java/com/softeer/caart/domain/option/repository/CarOptionRepository.java
  backend/src/main/java/com/softeer/caart/domain/trim/Trim.java
  backend/src/main/java/com/softeer/caart/domain/trim/controller/TrimController.java
  backend/src/main/java/com/softeer/caart/domain/trim/dto/MainOptionResponse.java
  backend/src/main/java/com/softeer/caart/domain/trim/dto/TrimResponse.java
  backend/src/main/java/com/softeer/caart/domain/trim/entity/AvailableColor.java
  backend/src/main/java/com/softeer/caart/domain/trim/entity/MainOptionOfTrim.java
  backend/src/main/java/com/softeer/caart/domain/trim/entity/Trim.java
  backend/src/main/java/com/softeer/caart/domain/trim/repository/MainOptionOfTrimRepository.java
  backend/src/main/java/com/softeer/caart/domain/trim/repository/TrimRepository.java
  backend/src/main/java/com/softeer/caart/domain/trim/service/TrimService.java
  backend/src/test/java/com/softeer/caart/domain/color/entity/ColorTest.java
  backend/src/test/java/com/softeer/caart/domain/common/RepositoryTest.java
  backend/src/test/java/com/softeer/caart/domain/common/ServiceTest.java
  backend/src/test/java/com/softeer/caart/domain/composition/service/CompositionServiceTest.java
  backend/src/test/java/com/softeer/caart/domain/trim/repository/TrimRepositoryTest.java
  backend/src/test/java/com/softeer/caart/domain/trim/service/TrimServiceTest.java
Labels: 기능개발 👨‍💻

#133 [FE] feat: 다시 추천받기 모달 구현
  frontend/public/images/re_recommend_icon.svg
  frontend/src/components/common/SquareButton.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/RerecommendButton.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/RerecommendModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCarImage.tsx
Labels: 기능개발 👨‍💻

#143 [FE] rename: 프론트엔드 파일명 수정
  frontend/src/components/common/header/HeaderDetail.tsx
  frontend/src/components/common/header/HeaderMain.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/NavBar.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/OptionCard.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/OptionCardTag.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/OptionCardListAdditionalAll.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModalTitle.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/util/PriceToString.ts
  frontend/src/util/TruncateString.ts
Labels: 수정 🛠

#149 [AOS] feat: 자동차 트림 페이지 - 엔진, 바디, 구동 방식 구현
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CarColorChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CarTrimChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/HomeFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodels/CarTrimChoiceViewModel.kt
  Android/app/src/main/res/drawable/ic_question_mark_16.xml
  Android/app/src/main/res/drawable/img_car_trim.png
  Android/app/src/main/res/drawable/selector_radio_btn_background.xml
  Android/app/src/main/res/drawable/selector_radio_btn_text_color.xml
  Android/app/src/main/res/drawable/shape_round8_background_gray300.xml
  Android/app/src/main/res/layout/fragment_car_trim_choice.xml
  Android/app/src/main/res/layout/fragment_home.xml
  Android/app/src/main/res/layout/layout_engine_body_drive_option.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#156 [FE] feat: 기본 옵션 화면 구현
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/OptionCard.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/OptionCardList.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/OptionCardListAdditionalTag.tsx
  frontend/src/pages/vehicleEstimationPage/OptionEstimationPage.tsx
Labels: 기능개발 👨‍💻

#157 [FE] feat: 버튼 컴포넌트 구현
  frontend/public/images/360_img.svg
  frontend/public/images/ex_img.svg
  frontend/public/images/in_img.svg
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/button/ColorButton.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/button/OptionButton.tsx
Labels: 기능개발 👨‍💻

#150 [BE] fix: CD workflow 수정
  .github/workflows/backend-deploy.yml
  backend/.gitignore
  backend/appspec.yml
  backend/build.gradle
  backend/scripts/start.sh
Labels: 수정 🛠

#153 [AOS] design: 옵션화면 - 상세옵션 다이얼로그 - 커스텀 클래스 제작
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/org/softeer_2nd/caArt/factorys/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/HomeFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/CarOptionChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/CircleIndicator.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/SelectLongButton.kt
  Android/app/src/main/res/drawable/ic_check_circle_16.xml
  Android/app/src/main/res/drawable/ic_small_x_24.xml
  Android/app/src/main/res/drawable/shape_option_check_long_btn_bakcground_180_blue.xml
  Android/app/src/main/res/drawable/shape_option_detail_background_16.xml
  Android/app/src/main/res/layout/fragment_car_option_choice.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/main/res/values/attrs.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/style_view.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#162 [FE] feat: 드롭다운 컴포넌트 구현
  frontend/public/images/dropdown_icon.svg
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/Dropdown.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/button/ColorButton.tsx
  frontend/src/pages/vehicleEstimationPage/ColorEstimationPage.tsx
  frontend/src/style/index.css
Labels: 기능개발 👨‍💻

#159 [AOS] feat: 트림옵션 선택 기능 구현
  Android/app/src/main/java/org/softeer_2nd/caArt/factorys/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/models/OptionTrimSelectionDummyItem.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/recyclerAdapters/TrimOptionSelectionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CarTrimChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodels/CarTrimChoiceViewModel.kt
  Android/app/src/main/res/layout/fragment_car_trim_choice.xml
  Android/app/src/main/res/layout/item_trim_select.xml
  Android/app/src/main/res/layout/layout_engine_body_drive_option.xml
  Android/app/src/main/res/layout/layout_more_trim_detail.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#161 [FE] feat: 옵션 더 알아보기 모달 구현
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/OptionCard.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/OptionCardList.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/OptionCardListAdditionalTag.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionInfoPopup/OptionInfoPopup.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionInfoPopup/OptionInfoPopupBtn.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModal.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModalTitle.tsx
  frontend/src/pages/vehicleEstimationPage/OptionEstimationPage.tsx
Labels: 기능개발 👨‍💻

#160 [AOS] feat: 옵션 상세 다이얼로그 UI 완료
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/ImageViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/TextViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/ViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dataClasses/Option.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dataClasses/event/OptionSelectEvent.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/dialogs/OptionDetailDialog.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/interfaces/OnRecyclerItemClickListener.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/recyclerAdapters/OptionDetailPageAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/recyclerAdapters/OptionDetailTextIndicatorAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/HomeFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/CircleIndicator.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/SelectLongButton.kt
  Android/app/src/main/res/layout/item_option_detail.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
Labels: 디자인 🖌

#176 [FE] feat: 색상 변경 팝업 구현
  frontend/src/components/common/SquareButton.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/ColorChangePopup.tsx
  frontend/src/pages/vehicleEstimationPage/ColorEstimationPage.tsx
Labels: 기능개발 👨‍💻

#175 [FE] feat: 360 회전 이미지 구현
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/CarRotator.tsx
Labels: 기능개발 👨‍💻

#178 [FE] feat: 라이프스타일 카드 컴포넌트 구현
  frontend/src/components/recommendPage/lifeStyleCard/LifeStyleCard.tsx
  frontend/src/components/recommendPage/recommendPage.txt
Labels: 기능개발 👨‍💻

#185 [FE] feat: 기본 컴포넌트 배치
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/ColorContainer.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/LeftCarImageContainer.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/button/OptionButton.tsx
  frontend/src/pages/vehicleEstimationPage/ColorEstimationPage.tsx
Labels: 기능개발 👨‍💻

#182 [BE] refactor: response의 key값 구체화
  backend/src/main/java/com/softeer/caart/domain/color/dto/ColorResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/BodyTypeResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/CarEngineResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/WheelDriveResponse.java
  backend/src/main/java/com/softeer/caart/domain/option/dto/CarOptionResponse.java
  backend/src/main/java/com/softeer/caart/domain/option/dto/ChildCarOptionResponse.java
  backend/src/main/java/com/softeer/caart/domain/trim/dto/MainOptionResponse.java
  backend/src/main/java/com/softeer/caart/domain/trim/dto/TrimResponse.java
  backend/src/main/java/com/softeer/caart/domain/trim/service/TrimService.java
  backend/src/test/java/com/softeer/caart/domain/composition/service/CompositionServiceTest.java
  backend/src/test/java/com/softeer/caart/domain/option/service/CarOptionServiceTest.java
  backend/src/test/java/com/softeer/caart/domain/trim/service/TrimServiceTest.java
Labels: 리팩토링 🔧

#180 [FE] feat: 라이프스타일 엿보기 컴포넌트 구현
  frontend/src/components/common/Tag.tsx
  frontend/src/components/common/TagList.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekForYou.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekInterview.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekModal.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekProfile.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekTitle.tsx
  frontend/src/style/index.css
Labels: 기능개발 👨‍💻

#187 [FE] feat: 나이 질문 페이지 구현
  frontend/src/components/common/SquareButton.tsx
  frontend/src/components/recommendPage/ageAndLifeStyle/PageNum.tsx
  frontend/src/components/recommendPage/ageAndLifeStyle/ReccomendPageButton.tsx
  frontend/src/pages/recommendPage/ReccomendAgePage.tsx
  frontend/src/style/index.css
Labels: 기능개발 👨‍💻

#189 [FE] feat: 이미지 컨테이너 구현
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/CarRotator.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/LeftCarImageContainer.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/button/OptionButton.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/colorEstimationPage.txt
Labels: 기능개발 👨‍💻

#193 [FE] feat: 라이프스타일 질문 페이지 구현
  frontend/src/components/recommendPage/lifeStyleCard/LifeStyleCard.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekModal.tsx
  frontend/src/pages/recommendPage/RecomendLifeStylePage.tsx
Labels: 기능개발 👨‍💻

#192 [AOS] design: 플로팅 옵션 구현 #110
  Android/app/src/main/java/org/softeer_2nd/caArt/dataBindingAdapters/ViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/factorys/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CarOptionChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/HomeFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/DynamicOptionFloatingButton.kt
  Android/app/src/main/res/drawable/ic_plus_20.xml
  Android/app/src/main/res/drawable/selector_option_floating_handle_background.xml
  Android/app/src/main/res/drawable/shape_option_floating_tootip_background_8.xml
  Android/app/src/main/res/drawable/shape_rect_r8.xml
  Android/app/src/main/res/drawable/shape_triangle.xml
  Android/app/src/main/res/layout/fragment_home.xml
  Android/app/src/main/res/layout/layout_dynamic_option_floating_tooltip.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/main/res/values/colors.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#194 [AOS] feat: 트림 선택 화면 더 알아보기 기능 구현
  Android/app/src/main/java/org/softeer_2nd/caArt/factorys/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/models/OptionTrimMoreDetailDummyItem.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/recyclerAdapters/TrimOptionMoreDetailAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/recyclerAdapters/TrimOptionSelectionAdapter.kt
  Android/app/src/main/res/layout/layout_engine_body_drive_option.xml
  Android/app/src/main/res/layout/layout_more_trim_detail.xml
  Android/app/src/main/res/values/strings.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#198 [BE] refactor: option table 변경으로 인한 일괄 리팩토링
  backend/src/main/java/com/softeer/caart/domain/option/entity/AdditionalOptionInfo.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/BaseOptionInfo.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/SubOptionInfo.java
  backend/src/test/java/com/softeer/caart/domain/option/service/BaseOptionInfoServiceTest.java
Labels: 수정 🛠

#203 [BE] setting: 차량 데이터 생성 및 삽입
  backend/scripts/sql/1_model.sql
  backend/scripts/sql/2_colors.sql
  backend/scripts/sql/3_tag.sql
  backend/scripts/sql/4_additional_options.sql
  backend/scripts/sql/5_sub_options.sql
  backend/scripts/sql/6_base_options.sql
  backend/scripts/sql/create.sql
Labels: 기능개발 👨‍💻

#212 [FE] feat: 라이프스타일 추가 설문 페이지 구현
  frontend/src/components/recommendPage/ageAndLifeStyle/RecommendPageButton.tsx
  frontend/src/pages/recommendPage/RecommendDetailPage.tsx
  frontend/src/pages/recommendPage/RecommendLifeStylePage.tsx
Labels: 기능개발 👨‍💻

#213 [FE] feat: 차량 선택 완료 컴포넌트 구현
  frontend/public/images/download_icon.svg
  frontend/public/images/dropdown_icon_silver.svg
  frontend/public/images/temp_top_image.png
  frontend/public/images/triangle.svg
  frontend/src/components/common/SquareButton.tsx
  frontend/src/components/resultPage/BuyCarContainer.tsx
  frontend/src/components/resultPage/ResultImage.tsx
  frontend/src/components/resultPage/TopContainer.tsx
  frontend/src/components/resultPage/resultPage.txt
  frontend/src/pages/resultPage/ResultPage.tsx
  frontend/src/style/index.css
Labels: 기능개발 👨‍💻

#214 [FE] fix: useFetch함수 수정
  frontend/src/hooks/useFetch.ts
Labels: 버그 🪲, 긴급 🚨

#217 [AOS] chore: 레트로핏 설정
  Android/app/build.gradle
  Android/app/src/main/java/org/softeer_2nd/caArt/retrofit/CaArtResponse.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/retrofit/CompositionService.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/retrofit/OptionService.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/retrofit/RetrofitClient.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/retrofit/TrimService.kt
Labels: 설계 📐

#205 [AOS] fix: 트러블 슈팅
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/CarColorChoiceFragment.kt
  Android/app/src/main/res/layout/fragment_car_color_choice.xml
  Android/app/src/main/res/layout/item_color_select.xml
Labels: 버그 🪲, 수정 🛠

#220 [BE] fix: cors 설정 추가
  backend/src/main/java/com/softeer/caart/global/config/CorsConfig.java
Labels: 버그 🪲

#209 [BE] feat: 태그 목록 조회 API 개발
  backend/src/main/java/com/softeer/caart/domain/option/entity/OptionTag.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/Position.java
  backend/src/main/java/com/softeer/caart/domain/tag/controller/TagController.java
  backend/src/main/java/com/softeer/caart/domain/tag/dto/TagResponse.java
  backend/src/main/java/com/softeer/caart/domain/tag/entity/Tag.java
  backend/src/main/java/com/softeer/caart/domain/tag/repository/TagRepository.java
  backend/src/main/java/com/softeer/caart/domain/tag/service/TagService.java
Labels: 기능개발 👨‍💻

#224 [AOS] feat: 트림 설명 화면 구현
  Android/app/src/main/java/org/softeer_2nd/caArt/models/dummys/TrimDescriptionDummyItem.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/models/factorys/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/fragments/CarTrimChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/fragments/CarTrimDescriptionFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/recyclerAdapters/TrimDescriptionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/recyclerAdapters/TrimDescriptionPagerAdapter.kt
  Android/app/src/main/res/drawable/shape_dailog_text_gray_background.xml
  Android/app/src/main/res/drawable/shape_dialog_text_blue_background.xml
  Android/app/src/main/res/layout/dialog_caart.xml
  Android/app/src/main/res/layout/fragment_car_trim_description.xml
  Android/app/src/main/res/layout/fragment_home.xml
  Android/app/src/main/res/layout/item_trim_description.xml
  Android/app/src/main/res/layout/item_trim_description_pager.xml
  Android/app/src/main/res/layout/layout_more_trim_detail.xml
  Android/app/src/main/res/layout/layout_other_color_option.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/main/res/values/strings.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#226 [AOS] design: 옵션화면 ui제작1
  Android/app/src/main/java/org/softeer_2nd/caArt/views/custom/DynamicOptionFloatingButton.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/custom/DynamicOptionFloatingImageView.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/fragments/HomeFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/recyclerAdapters/OptionTagRecyclerAdapter.kt
  Android/app/src/main/res/drawable/ic_arrow_right_14.xml
  Android/app/src/main/res/drawable/shape_option_tag_item_background_r16_blue.xml
  Android/app/src/main/res/drawable/shape_rect_r4.xml
  Android/app/src/main/res/layout/fragment_home.xml
  Android/app/src/main/res/layout/item_option_tag.xml
  Android/app/src/main/res/layout/layout_dynamic_option_floating_tooltip.xml
  Android/app/src/main/res/values/strings.xml
Labels: 디자인 🖌

#229 [AOS] 트림 상세 설명 페이지 탭 레이아웃
  Android/app/src/main/java/org/softeer_2nd/caArt/models/dummys/TrimDescriptionDummyItem.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/models/factorys/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/fragments/CarTrimDescriptionFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/recyclerAdapters/TrimDescriptionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/recyclerAdapters/TrimDescriptionPagerAdapter.kt
  Android/app/src/main/res/drawable/shape_dailog_text_background_gray700.xml
  Android/app/src/main/res/drawable/shape_dialog_text_background_blue.xml
  Android/app/src/main/res/layout/dialog_caart.xml
  Android/app/src/main/res/layout/fragment_car_trim_description.xml
  Android/app/src/main/res/layout/fragment_home.xml
  Android/app/src/main/res/layout/item_trim_description.xml
  Android/app/src/main/res/layout/item_trim_description_pager.xml
  Android/app/src/main/res/layout/layout_more_trim_detail.xml
  Android/app/src/main/res/layout/layout_other_color_option.xml
Labels: 기능개발 👨‍💻

#233 [AOS] design: 옵션 화면 UI 제작 2
  Android/app/src/main/java/org/softeer_2nd/caArt/views/dataBindingAdapters/ImageViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/fragments/CarOptionChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/recyclerAdapters/OptionPreviewRecyclerAdapter.kt
  Android/app/src/main/res/layout/fragment_car_option_choice.xml
  Android/app/src/main/res/layout/item_option_preivew_see_more.xml
  Android/app/src/main/res/layout/item_option_preview.xml
  Android/app/src/main/res/layout/item_situation_options_option.xml
  Android/app/src/main/res/layout/layout_situational_tag_options.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#234 [AOS] feat: 첫 진입 화면 구현
  Android/app/src/main/java/org/softeer_2nd/caArt/views/custom/SummaryBottomSheet.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/dataBindingAdapters/TextViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/fragments/CarColorChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/fragments/CarOptionChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/fragments/CarTrimChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/fragments/HomeFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/recyclerAdapters/TrimDescriptionPagerAdapter.kt
  Android/app/src/main/res/drawable/shape_video_shadow.xml
  Android/app/src/main/res/layout/activity_main.xml
  Android/app/src/main/res/layout/fragment_car_color_choice.xml
  Android/app/src/main/res/layout/fragment_car_option_choice.xml
  Android/app/src/main/res/layout/fragment_car_trim_choice.xml
  Android/app/src/main/res/layout/fragment_home.xml
  Android/app/src/main/res/layout/layout_bottom_sheet_up.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/styles_button.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#230 [BE] refactor: 태그 목록 조회 API의 response에서 불필요한 key 삭제
  backend/src/main/java/com/softeer/caart/domain/tag/dto/TagResponse.java
  backend/src/main/java/com/softeer/caart/domain/tag/entity/Tag.java
  backend/src/main/java/com/softeer/caart/domain/tag/service/TagService.java
  backend/src/test/java/com/softeer/caart/domain/common/ServiceTest.java
  backend/src/test/java/com/softeer/caart/domain/tag/service/TagServiceTest.java
Labels: 리팩토링 🔧

#238 [AOS] refactor: PR #233, #160 피드백 반영
  Android/app/src/main/java/org/softeer_2nd/caArt/views/dialogs/OptionDetailDialog.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/recyclerAdapters/OptionDetailPageAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/views/recyclerAdapters/OptionPreviewRecyclerAdapter.kt
  Android/app/src/main/res/layout/item_situation_options_option.xml
  Android/app/src/main/res/layout/layout_situational_tag_options.xml
Labels: 리팩토링 🔧

#218 [FE] feat: 라이프스타일 엿보기 팝업 오류 수정
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekModal.tsx
Labels: 버그 🪲

#223 [FE] feat: 추가 질문 기반 추천 제안 완료 페이지 구현
  frontend/src/pages/recommendPage/RecommendDetailResultPage.tsx
Labels: 기능개발 👨‍💻

#225 [FE] feat: 추천 제안 페이지, 데이터 이동 구현
  frontend/src/App.tsx
  frontend/src/components/recommendPage/ageAndLifeStyle/RecommendPageButton.tsx
  frontend/src/components/recommendPage/ageAndLifeStyle/SlideBar.tsx
  frontend/src/components/recommendPage/lifeStyleCard/LifeStyleCard.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekModal.tsx
  frontend/src/pages/recommendPage/RecommendAgePage.tsx
  frontend/src/pages/recommendPage/RecommendDetailPage.tsx
  frontend/src/pages/recommendPage/RecommendDetailResultPage.tsx
  frontend/src/pages/recommendPage/RecommendLifeStylePage.tsx
  frontend/src/pages/recommendPage/RecommendLifeStyleResultPage.tsx
  frontend/src/pages/recommendPage/RecommendPage.tsx
  frontend/src/pages/vehicleEstimationPage/VehicleEstimationPage.tsx
Labels: 기능개발 👨‍💻, 설계 📐

#239 [BE] feat: logging 전략 수립
  backend/build.gradle
  backend/src/main/java/com/softeer/caart/CaArtServerApplication.java
  backend/src/main/java/com/softeer/caart/global/config/LoggingConfig.java
  backend/src/main/java/com/softeer/caart/global/handler/GlobalExceptionHandler.java
Labels: 기능개발 👨‍💻

#248 [FE] refactor: 옵션 선택 페이지 1차 리팩토링 - 2
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekModal.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/OptionCardListAdditionalTag.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionInfoPopup/OptionInfoPopup.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionInfoPopup/OptionInfoPopupBtn.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModal.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModalDetail.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModalTitle.tsx
  frontend/src/hooks/useModal.ts
  frontend/src/pages/vehicleEstimationPage/OptionEstimationPage.tsx
Labels: 리팩토링 🔧, 설계 📐

#250 [FE] feat: 트림 페이지 api연동
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWGuideModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/OuterColorContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
Labels: 기능개발 👨‍💻

#257 [BE] refactor: API 응답 형태 수정
  backend/src/main/java/com/softeer/caart/domain/composition/controller/CompositionController.java
  backend/src/main/java/com/softeer/caart/domain/option/controller/OptionController.java
  backend/src/main/java/com/softeer/caart/domain/tag/controller/TagController.java
  backend/src/main/java/com/softeer/caart/domain/trim/controller/TrimController.java
  backend/src/main/java/com/softeer/caart/global/response/DataResponseDto.java
Labels: 리팩토링 🔧, 긴급 🚨

#256 [BE] feat: 라이프스타일 페르소나 목록 조회 API 개발
  backend/scripts/sql/3_tag.sql
  backend/scripts/sql/4_additional_options.sql
  backend/scripts/sql/5_sub_options.sql
  backend/scripts/sql/6_base_options.sql
  backend/scripts/sql/7_model_options.sql
  backend/scripts/sql/8_persona.sql
  backend/scripts/sql/create.sql
  backend/src/main/java/com/softeer/caart/domain/composition/entity/BodyType.java
  backend/src/main/java/com/softeer/caart/domain/composition/entity/CarEngine.java
  backend/src/main/java/com/softeer/caart/domain/composition/entity/WheelDrive.java
  backend/src/main/java/com/softeer/caart/domain/lifestyle/persona/controller/PersonaController.java
  backend/src/main/java/com/softeer/caart/domain/lifestyle/persona/dto/PersonaResponse.java
  backend/src/main/java/com/softeer/caart/domain/lifestyle/persona/entity/Persona.java
  backend/src/main/java/com/softeer/caart/domain/lifestyle/persona/entity/Profile.java
  backend/src/main/java/com/softeer/caart/domain/lifestyle/persona/entity/RecommendationResult.java
  backend/src/main/java/com/softeer/caart/domain/lifestyle/persona/repository/PersonaRepository.java
  backend/src/main/java/com/softeer/caart/domain/lifestyle/persona/service/PersonaService.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/AdditionalOptionInfo.java
  backend/src/main/java/com/softeer/caart/domain/trim/entity/Trim.java
Labels: 기능개발 👨‍💻

#261 [BE] feat: HTTPS 연결
  .github/workflows/backend-deploy.yml
  backend/src/main/java/com/softeer/caart/global/config/CorsConfig.java
  backend/src/main/java/com/softeer/caart/global/config/SwaggerConfig.java
Labels: 기능개발 👨‍💻

#260 [FE] fix: 비교하기 모달 오류 수정
  frontend/public/images/carComponent/18_wheel.svg
  frontend/public/images/carComponent/wheel.svg
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/CompareModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWGuideModal.tsx
  frontend/src/hooks/useFetch.ts
  frontend/src/hooks/useModal.ts
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
Labels: 수정 🛠

#266 [FE] fix: api 수정에 따른 함수 변경
  frontend/public/index.html
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/CompareModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWGuideModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimContainer.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
Labels: 수정 🛠

#267 [AOS] design: 사전 질문 화면 ui구현
  Android/app/src/main/java/org/softeer_2nd/caArt/model/network/TrimApiService.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/repository/CarTrimRepository.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/fragment/CarOptionChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/fragment/LifeStyleSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/recyclerAdapter/SurveyAnswerOptionsRecyclerAdapter.kt
  Android/app/src/main/res/drawable/ic_check_circle_24_blue.xml
  Android/app/src/main/res/drawable/ic_checked_28.xml
  Android/app/src/main/res/drawable/ic_unchecked_28.xml
  Android/app/src/main/res/drawable/shape_survey_answer_option_background_r6_blue.xml
  Android/app/src/main/res/drawable/shape_survey_text_indicator_background_r22_gray900.xml
  Android/app/src/main/res/layout/fragment_survey.xml
  Android/app/src/main/res/layout/item_trim_select.xml
  Android/app/src/main/res/navigation/nav_graph.xml
Labels: 디자인 🖌

#269 [FE] feat: 옵션 모달 수정
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/OptionExplainModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimContainer.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
  frontend/src/style/reset.css
Labels: 기능개발 👨‍💻

#270 [FE] feat: 기본 옵션 세부정보 API 연동
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModal.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModalTitle.tsx
  frontend/src/pages/vehicleEstimationPage/OptionEstimationPage.tsx
Labels: 기능개발 👨‍💻

#276 [FE] feat: 트림 페이지 애니메이션 추가
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/CompareModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWGuideModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/OptionExplainModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/RerecommendModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCarImage.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
Labels: 기능개발 👨‍💻

#273 [AOS] feat: 트림 선택 페이지 API 연동 및 기존 버그 수정
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Trim.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/TrimItemColor.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/TrimMainItem.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/dummy/OptionTrimSelectionDummyItem.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/network/CaArtResponse.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/repository/CarTrimRepository.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/bindingAdapter/TextViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/callbackListener/OnTrimItemClickListener.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/fragment/CarTrimChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/recyclerAdapter/TrimOptionMoreDetailAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/recyclerAdapter/TrimOptionSelectionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/CarTrimChoiceViewModel.kt
  Android/app/src/main/res/layout/fragment_car_trim_choice.xml
  Android/app/src/main/res/layout/item_trim_select.xml
Labels: 버그 🪲, 기능개발 👨‍💻, 수정 🛠

#278 [FE] feat: 페이지 라우팅 구조 설계
  frontend/src/App.tsx
  frontend/src/components/common/ErrorPopup.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/LeftCarImageContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCarImage.tsx
  frontend/src/components/vehicleEstimationPage/vehicleEstimationPage.txt
  frontend/src/pages/homePage/HomePage.tsx
  frontend/src/pages/recommendPage/RecommendDetailResultPage.tsx
  frontend/src/pages/recommendPage/RecommendLifeStyleResultPage.tsx
  frontend/src/pages/recommendPage/RecommendPage.tsx
  frontend/src/pages/resultPage/ResultPage.tsx
  frontend/src/pages/vehicleEstimationPage/ColorEstimationPage.tsx
  frontend/src/pages/vehicleEstimationPage/OptionEstimationPage.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
  frontend/src/pages/vehicleEstimationPage/VehicleEstimationPage.tsx
Labels: 기능개발 👨‍💻, 설계 📐

#275 [AOS] feat: Process관련 클래스 설계 (ProcessViewModel,ProcessFargment)
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/event/ProcessChangeEvent.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/event/SurveyQuestion.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/fragment/HomeFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/fragment/LifeStyleSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/fragment/ProcessFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/LifeStyleSurveyViewModel.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/ProcessViewModel.kt
  Android/app/src/main/res/layout/fragment_survey.xml
Labels: 리팩토링 🔧, 설계 📐

#282 [AOS] feat: Glide->Coil로 이전 #155
  Android/app/build.gradle
  Android/app/src/main/java/org/softeer_2nd/caArt/model/network/RetrofitClient.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/bindingAdapter/ImageViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/fragment/CarOptionChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/recyclerAdapter/TrimDescriptionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/recyclerAdapter/TrimOptionMoreDetailAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/CarColorChoiceViewModel.kt
Labels: 리팩토링 🔧

#286 [FE] feat: 라이프스타일 API 연동
  frontend/src/components/recommendPage/lifeStyleCard/LifeStyleCard.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekModal.tsx
  frontend/src/pages/recommendPage/RecommendLifeStylePage.tsx
  frontend/src/pages/recommendPage/RecommendPage.tsx
  frontend/src/util/ReplaceWonSymbol.ts
Labels: 기능개발 👨‍💻

#283 [AOS] design: 추천 제안 사전질문 화면 UI, UDF 데이터 플로우구현
  Android/app/build.gradle
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Persona.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/network/RetrofitClient.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/bindingAdapter/ImageViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/fragment/LifeStyleSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/recyclerAdapter/LifestylePersonaSelectAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/LifeStyleSurveyViewModel.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/ProcessViewModel.kt
  Android/app/src/main/res/drawable/shape_life_style_persona_image_background_oval_blue.xml
  Android/app/src/main/res/drawable/shape_life_style_persona_tag_background_r100_transparent_blue.xml
  Android/app/src/main/res/drawable/shape_stroke_background_r16_blue.xml
  Android/app/src/main/res/layout/fragment_survey.xml
  Android/app/src/main/res/layout/item_life_style_no_persona.xml
  Android/app/src/main/res/layout/item_life_style_persona.xml
  Android/app/src/main/res/layout/item_option_tag.xml
  Android/app/src/main/res/layout/layout_life_style_persona_container.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/styles_textView.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#288 [FE] refactor: 공통 컴포넌트 생성 및 컴포넌트 수정
  frontend/src/components/common/FlexBox.tsx
  frontend/src/components/common/Hr.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/CarRotator.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/ColorChangePopup.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/button/OptionButton.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/CompareModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWGuideModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/OuterColorContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/RerecommendModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/static/data/CompareModalData.ts
Labels: 리팩토링 🔧, 수정 🛠

#293 [FE] refactor: 색상선택 페이지 디자인 개선
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/ColorChangePopup.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/Dropdown.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/LeftCarImageContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/RerecommendModal.tsx
  frontend/src/hooks/useDetectClose.ts
  frontend/src/pages/vehicleEstimationPage/ColorEstimationPage.tsx
Labels: 기능개발 👨‍💻, 리팩토링 🔧, 디자인 🖌

#299 [BE] feat: 페르소나 상세 조회 API 개발
  backend/build.gradle
  backend/src/main/java/com/softeer/caart/domain/model/Model.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/controller/PersonaController.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/dto/PersonaDetailsResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/entity/Persona.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/entity/RecommendationResult.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/exception/PersonaNotFoundException.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/service/PersonaService.java
  backend/src/main/java/com/softeer/caart/global/ResultCode.java
  backend/src/main/java/com/softeer/caart/global/exception/BusinessException.java
  backend/src/test/java/com/softeer/caart/domain/common/ServiceTest.java
  backend/src/test/java/com/softeer/caart/domain/recommendation/persona/PersonaServiceTest.java
Labels: 기능개발 👨‍💻

#290 [FE] feat: 헤더 컴포넌트 최종 개선 및 구현
  frontend/public/images/scroll_icon_black.svg
  frontend/src/components/common/Logo.tsx
  frontend/src/components/common/header/DropDown.tsx
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/header/HeaderDetail.tsx
  frontend/src/components/common/header/HeaderMain.tsx
  frontend/src/components/common/header/HeaderProgressBar.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekModal.tsx
  frontend/src/pages/homePage/HomePage.tsx
  frontend/src/pages/recommendPage/RecommendAgePage.tsx
  frontend/src/pages/recommendPage/RecommendDetailPage.tsx
  frontend/src/pages/recommendPage/RecommendDetailResultPage.tsx
  frontend/src/pages/recommendPage/RecommendLifeStylePage.tsx
  frontend/src/pages/recommendPage/RecommendLifeStyleResultPage.tsx
  frontend/src/pages/recommendPage/RecommendPage.tsx
  frontend/src/pages/vehicleEstimationPage/ColorEstimationPage.tsx
  frontend/src/pages/vehicleEstimationPage/OptionEstimationPage.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
Labels: 기능개발 👨‍💻, 리팩토링 🔧, 설계 📐

#306 [BE] feat: 페르소나별 추천 견적 조회 API 개발
  .github/workflows/backend-test.yml
  backend/src/main/java/com/softeer/caart/domain/model/Model.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/RecommendedDto.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/controller/PersonaController.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/dto/PersonaDetailsResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/dto/PersonaRecommendationResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/entity/RecommendationResult.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/service/PersonaService.java
Labels: 기능개발 👨‍💻

#307 [BE] feat: 기본옵션 목록 조회 API 개발
  backend/src/main/java/com/softeer/caart/domain/option/controller/OptionController.java
  backend/src/main/java/com/softeer/caart/domain/option/dto/AdditionalOptionsResponse.java
  backend/src/main/java/com/softeer/caart/domain/option/dto/BasicOptionResponse.java
  backend/src/main/java/com/softeer/caart/domain/option/dto/BasicOptionsResponse.java
  backend/src/main/java/com/softeer/caart/domain/option/dto/OptionListRequest.java
  backend/src/main/java/com/softeer/caart/domain/option/repository/BaseOptionInfoRepository.java
  backend/src/main/java/com/softeer/caart/domain/option/service/OptionService.java
  backend/src/test/java/com/softeer/caart/domain/option/service/OptionServiceTest.java
Labels: 기능개발 👨‍💻

#308 [BE] 라이프스타일 기반 추천 견적 조회 API 개발
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/controller/LifeStyleController.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/LifestyleQuestionDto.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/request/RecommendationRequest.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/response/LifestyleAdditionalQuestionsResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/response/LifestyleBaseQuestionsResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/response/RecommendationResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/entity/QuestionType.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/repository/RecommendationResultRepository.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/service/LifeStyleService.java
Labels: 기능개발 👨‍💻

#300 [AOS] 사전질문, 추가질문 UI구성끝 #285
  Android/app/src/main/java/org/softeer_2nd/caArt/CaArtApplication.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/BudgetRange.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/util/StringFormatter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/bindingAdapter/ImageViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/bindingAdapter/SliderBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/fragment/LifeStyleDetailSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/view/fragment/LifeStyleSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/LifeStyleDetailSurveyViewModel.kt
  Android/app/src/main/res/layout/fragment_survey.xml
  Android/app/src/main/res/layout/layout_detail_survey_set_budget.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/main/res/values/themes.xml
Labels: 디자인 🖌

#313 [FE] feat: 라이프스타일 페르소나 모달 API 연동
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekForYou.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekInterview.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekModal.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekProfile.tsx
  frontend/src/components/recommendPage/lifeStylePeek/LifeStylePeekTitle.tsx
  frontend/src/pages/homePage/HomePage.tsx
  frontend/src/pages/recommendPage/RecommendLifeStylePage.tsx
Labels: 기능개발 👨‍💻

#315 [FE] fix: 헤더 애니메이션 버그 수정
  frontend/src/components/common/header/DropDown.tsx
Labels: 버그 🪲, 긴급 🚨

#322 [BE] fix: native query 수정
  backend/src/main/java/com/softeer/caart/domain/model/repository/ModelRepository.java
Labels: 버그 🪲, 긴급 🚨

#327 [AOS] feat: 옵션 구조 설계 및 옵션태그 api연동
  Android/app/build.gradle
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/OptionTag.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/di/NetworkModule.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/network/OptionApiService.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/repository/CarOptionRepository.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/ImageViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/CarOptionChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/LifeStyleSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/OptionTagRecyclerAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/CarOptionChoiceViewModel.kt
  Android/app/src/main/res/layout/item_option_tag.xml
Labels: 기능개발 👨‍💻

#326 [BE] feat: 라이프스타일 API - 요청 검증, 연령 및 가격 정보 추가
  backend/src/main/java/com/softeer/caart/domain/composition/controller/CompositionController.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/BodyTypeDto.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/CarEngineDto.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/WheelDriveDto.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/BodyTypeResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/CarEngineResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/CompositionResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/WheelDriveResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/service/CompositionService.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/controller/LifeStyleController.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/RecommendedDto.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/request/RecommendationRequest.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/controller/PersonaController.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/service/PersonaService.java
  backend/src/main/java/com/softeer/caart/domain/trim/controller/TrimController.java
  backend/src/main/java/com/softeer/caart/domain/trim/dto/TrimDto.java
  backend/src/main/java/com/softeer/caart/domain/trim/dto/response/MainOptionResponse.java
  backend/src/main/java/com/softeer/caart/domain/trim/dto/response/TrimResponse.java
  backend/src/main/java/com/softeer/caart/domain/trim/service/TrimService.java
  backend/src/main/java/com/softeer/caart/global/ResultCode.java
  backend/src/main/java/com/softeer/caart/global/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/softeer/caart/global/response/ErrorListResponseDto.java
  backend/src/main/java/com/softeer/caart/global/response/ErrorResponseDto.java
  backend/src/test/java/com/softeer/caart/domain/composition/service/CompositionServiceTest.java
  backend/src/test/java/com/softeer/caart/domain/trim/service/TrimServiceTest.java
Labels: 기능개발 👨‍💻

#331 [BE] fix: 실행 중인 애플리케이션이 있다면 kill하도록 CD 스크립트 수정
  backend/scripts/start.sh
Labels: 버그 🪲

#325 [FE] feat: 라이프스타일 페르소나 결과 API 연동
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/result/ResultCard.tsx
  frontend/src/components/common/result/ResultCardList.tsx
  frontend/src/components/common/result/ResultFooter.tsx
  frontend/src/components/common/result/ResultHeader.tsx
  frontend/src/components/recommendPage/ageAndLifeStyle/RecommendResultCard.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCard/OptionCard.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionModal/OptionModalTitle.tsx
  frontend/src/pages/recommendPage/RecommendLifeStylePage.tsx
  frontend/src/pages/recommendPage/RecommendLifeStyleResultPage.tsx
  frontend/src/util/Context.tsx
Labels: 기능개발 👨‍💻

#335 [FE] feat: 라이프스타일 사전 질문 API 연동
  frontend/src/pages/recommendPage/RecommendAgePage.tsx
Labels: 기능개발 👨‍💻

#338 [BE] fix: cors 허용 추가
  backend/src/main/java/com/softeer/caart/global/config/CorsConfig.java
Labels: 버그 🪲, 기능개발 👨‍💻, 긴급 🚨

#336 [AOS] feat: 옵션화면 api연동
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/AdditionalOptionResponseDTO.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/DefaultOptionResponseDTO.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Option.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Position.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/network/OptionApiService.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/repository/CarOptionRepository.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/ImageViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/callback/OnItemClickListener.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/DynamicOptionFloatingImageView.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/dialog/OptionDetailDialog.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/CarOptionChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/CarTrimDescriptionFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/OptionDetailPageAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/OptionPreviewRecyclerAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/OptionTagRecyclerAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/CarOptionChoiceViewModel.kt
  Android/app/src/main/res/layout/fragment_car_option_choice.xml
  Android/app/src/main/res/layout/item_option_detail.xml
  Android/app/src/main/res/layout/item_option_preview.xml
  Android/app/src/main/res/layout/item_situation_options_option.xml
  Android/app/src/main/res/layout/layout_dynamic_option_floating_tooltip.xml
  Android/app/src/main/res/layout/layout_situational_tag_options.xml
Labels: 기능개발 👨‍💻

#342 [AOS] 바텀 시트 사용자 선택 데이터 동기화
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Engine.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/TrimDescription.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/UserChoice.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/WheelDrive.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/dummy/OptionSelectionDummyItem.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/CarTrimChoiceBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/ViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/SummaryBottomSheet.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/CarTrimChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/CarTrimDescriptionFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/BottomSheetCurrentOptionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/TrimOptionSelectionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/util/StringFormatter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/util/UserChoiceConverter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/CarTrimDescriptionViewModel.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/UserChoiceViewModel.kt
  Android/app/src/main/res/layout/item_color_select.xml
  Android/app/src/main/res/layout/item_option_select.xml
  Android/app/src/main/res/layout/layout_bottom_sheet_down.xml
  Android/app/src/main/res/layout/layout_bottom_sheet_up.xml
  Android/app/src/main/res/layout/layout_dynamic_option_floating_tooltip.xml
  Android/app/src/main/res/layout/layout_engine_body_drive_option.xml
  Android/app/src/main/res/values/strings.xml
Labels: 기능개발 👨‍💻

#333 [BE] fix: 태그 목록 조회 API 수정
  backend/src/main/java/com/softeer/caart/domain/Image.java
  backend/src/main/java/com/softeer/caart/domain/tag/controller/TagController.java
  backend/src/main/java/com/softeer/caart/domain/tag/dto/TagResponse.java
  backend/src/main/java/com/softeer/caart/domain/tag/entity/Tag.java
  backend/src/main/java/com/softeer/caart/domain/tag/service/TagService.java
  backend/src/main/java/com/softeer/caart/global/config/SwaggerConfig.java
  backend/src/test/java/com/softeer/caart/domain/tag/service/TagServiceTest.java
Labels: 수정 🛠

#346 [AOS] feat: 옵션페이지 api연동 끝
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/state/SituationalOptionViewState.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/di/NetworkModule.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/repository/CarOptionRepository.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/ImageViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/DynamicOptionFloatingImageView.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/SelectLongButton.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/dialog/OptionDetailDialog.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/CarOptionChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/LifeStyleSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/OptionDetailPageAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/OptionPreviewRecyclerAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/util/UserChoiceConverter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/CarOptionChoiceViewModel.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/UserChoiceViewModel.kt
  Android/app/src/main/res/layout/item_option_detail.xml
  Android/app/src/main/res/layout/item_option_preview.xml
  Android/app/src/main/res/layout/item_option_tag.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#349 [BE] fix: 데이터셋 수정
  backend/scripts/sql/1_model.sql
  backend/scripts/sql/2_colors.sql
  backend/scripts/sql/3_options.sql
  backend/scripts/sql/3_tag.sql
  backend/scripts/sql/4_additional_options.sql
  backend/scripts/sql/4_model_options.sql
  backend/scripts/sql/4_trim_options.sql
  backend/scripts/sql/5_additional_options.sql
  backend/scripts/sql/5_position.sql
  backend/scripts/sql/5_sub_options.sql
  backend/scripts/sql/6_base_options.sql
  backend/scripts/sql/6_sub_options.sql
  backend/scripts/sql/7_model_options.sql
  backend/scripts/sql/7_tag.sql
  backend/scripts/sql/8_persona.sql
  backend/scripts/sql/8_tag_options.sql
  backend/scripts/sql/9_persona.sql
  backend/scripts/sql/create.sql
  backend/src/main/java/com/softeer/caart/domain/option/dto/AdditionalOptionWithPositionResponse.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/AdditionalOptionInfo.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/Position.java
  backend/src/test/java/com/softeer/caart/domain/common/ServiceTest.java
  backend/src/test/resources/sql/insert.sql
Labels: 설계 📐, 긴급 🚨, 수정 🛠

#357 [BE] fix: 데이터셋 수정
  backend/src/main/java/com/softeer/caart/domain/option/entity/Position.java
Labels: 버그 🪲, 긴급 🚨

#358 [BE] refactor: 추가 질문 목록 enum 분리 및 API 반영
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/LifestyleQuestionDto.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/response/LifestyleAdditionalQuestionsResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/response/LifestyleBaseQuestionsResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/entity/Answer.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/entity/Question.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/entity/QuestionType.java
Labels: 리팩토링 🔧

#353 [AOS] feat: 질문화면 api 연동
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Choice.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Persona.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/SurveyQuestion.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/dto/AdditionalOptionResponseDTO.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/dto/AdditionalSurveyQuestionResposne.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/dto/Budget.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/dto/DefaultOptionResponseDTO.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/dto/SurveyQuestionResponse.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/event/SurveyQuestion.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/di/NetworkModule.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/network/OptionApiService.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/network/RecommandApiService.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/repository/CarOptionRepository.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/repository/RecommandRepository.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/LifeStyleDetailSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/LifeStyleSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/LifestylePersonaSelectAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/SurveyAnswerOptionsRecyclerAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/LifeStyleDetailSurveyViewModel.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/LifeStyleSurveyViewModel.kt
  Android/app/src/main/res/layout/item_life_style_persona.xml
Labels: 기능개발 👨‍💻

#340 [FE] feat: 추천 제안 페이지 추가 질문 API 연동
  frontend/src/components/recommendPage/ageAndLifeStyle/RecommendResultCard.tsx
  frontend/src/components/recommendPage/ageAndLifeStyle/SlideBar.tsx
  frontend/src/pages/recommendPage/RecommendAgePage.tsx
  frontend/src/pages/recommendPage/RecommendDetailPage.tsx
  frontend/src/pages/recommendPage/RecommendPage.tsx
Labels: 기능개발 👨‍💻

#343 [FE] feat: 추천 제안 페이지 설문 결과 API 연동
  frontend/src/components/common/Tag.tsx
  frontend/src/components/common/TagList.tsx
  frontend/src/pages/recommendPage/RecommendDetailResultPage.tsx
Labels: 기능개발 👨‍💻

#345 [FE] feat: 옵션 선택 페이지 태그 API 연동
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/NavBarLower.tsx
Labels: 기능개발 👨‍💻

#362 [AOS] feat: 트림 선택 페이지 UI 개선
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/UserChoiceBottomsheetState.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/ButtonBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/CarColorChoiceBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/CarTrimChoiceBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/TextViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/ViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/ViewGroupBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/custom/SummaryBottomSheet.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/CarTrimChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/BottomSheetCurrentOptionAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/TrimOptionMoreDetailAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/util/UserChoiceConverter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/CarTrimChoiceViewModel.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/UserChoiceViewModel.kt
  Android/app/src/main/res/drawable/ic_bulb_32.xml
  Android/app/src/main/res/drawable/shape_down_arrow_nor.xml
  Android/app/src/main/res/layout/fragment_car_trim_choice.xml
  Android/app/src/main/res/layout/item_option_select.xml
  Android/app/src/main/res/layout/layout_bubble.xml
Labels: 기능개발 👨‍💻

#351 [FE] feat: 이미지 변경과 비교하기 API 연동
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/CompareModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/OptionExplainModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCarImage.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/static/data/CompareModalData.ts
  frontend/src/util/Context.tsx
Labels: 기능개발 👨‍💻

#356 [FE] refactor: 모달 상태 Context로 관리
  frontend/src/App.tsx
  frontend/src/components/common/ToolTip.tsx
  frontend/src/components/vehicleEstimationPage/colorEstimationPage/LeftCarImageContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/CompareModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWContainer.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/EBWGuideModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/OptionExplainModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/RerecommendButton.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/RerecommendModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCarImage.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCard.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimContainer.tsx
  frontend/src/pages/vehicleEstimationPage/TrimEstimationPage.tsx
  frontend/src/store/ModalContext.tsx
Labels: 기능개발 👨‍💻, 리팩토링 🔧

#365 [FE] feat: 결과 페이지 기능 추가
  frontend/src/components/common/SquareButton.tsx
  frontend/src/components/resultPage/BuyCarContainer.tsx
  frontend/src/components/resultPage/ResultImage.tsx
  frontend/src/components/resultPage/TopContainer.tsx
  frontend/src/components/resultPage/modal/LoginModal.tsx
  frontend/src/components/resultPage/modal/MailModal.tsx
  frontend/src/components/resultPage/modal/ShareModal.tsx
  frontend/src/components/vehicleEstimationPage/trimEstimationPage/TrimCarImage.tsx
  frontend/src/pages/resultPage/ResultPage.tsx
  frontend/src/store/ModalContext.tsx
Labels: 기능개발 👨‍💻, 수정 🛠

#367 [AOS] fix: 말풍선 드로어블 배경 추가
  Android/app/src/main/res/drawable/shape_bubble.xml
Labels: 수정 🛠

#364 [BE] feat: 카마스터 설문지 조회 API 개발
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/BodyTypeSummaryResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/CarEngineSummaryResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/CompositionSummaryResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/WheelDriveSummaryResponse.java
  backend/src/main/java/com/softeer/caart/domain/model/entity/AvailableOption.java
  backend/src/main/java/com/softeer/caart/domain/model/entity/Model.java
  backend/src/main/java/com/softeer/caart/domain/model/repository/ModelRepository.java
  backend/src/main/java/com/softeer/caart/domain/option/repository/AdditionalOptionInfoRepository.java
  backend/src/main/java/com/softeer/caart/domain/option/repository/BaseOptionInfoRepository.java
  backend/src/main/java/com/softeer/caart/domain/option/service/OptionService.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/carmaster/controller/CarMasterController.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/carmaster/dto/SurveyResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/carmaster/service/CarMasterService.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/LifestyleQuestionDto.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/RecommendedDto.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/entity/Answer.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/entity/Question.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/dto/PersonaDetailsResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/persona/entity/RecommendationResult.java
  backend/src/main/java/com/softeer/caart/domain/trim/dto/response/TrimSummaryResponse.java
  backend/src/main/java/com/softeer/caart/global/utils/RandomUtils.java
  backend/src/test/java/com/softeer/caart/domain/common/ServiceTest.java
  backend/src/test/java/com/softeer/caart/domain/model/ModelTest.java
  backend/src/test/java/com/softeer/caart/domain/model/repository/ModelRepositoryTest.java
  backend/src/test/java/com/softeer/caart/domain/recommendation/lifestyle/entity/QuestionTest.java
  backend/src/test/java/com/softeer/caart/domain/recommendation/persona/PersonaServiceTest.java
  backend/src/test/java/com/softeer/caart/global/utils/RandomUtilsTest.java
Labels: 기능개발 👨‍💻

#366 [FE] feat: 기본 / 추가 옵션 태그 API 분리
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/NavBarLower.tsx
Labels: 기능개발 👨‍💻

#371 [BE] refactor: 추가 옵션 목록 조회 시 뱃지와 채택률도 포함해서 response 하도록 수정
  backend/src/main/java/com/softeer/caart/domain/option/dto/AdditionalOptionWithPositionResponse.java
  backend/src/main/java/com/softeer/caart/domain/option/entity/AdditionalOptionInfo.java
Labels: 수정 🛠

#372 [BE] feat: 색상 목록 조회 API 개발
  backend/src/main/java/com/softeer/caart/domain/color/controller/ColorController.java
  backend/src/main/java/com/softeer/caart/domain/color/dto/ColorDto.java
  backend/src/main/java/com/softeer/caart/domain/color/dto/ColorResponse.java
  backend/src/main/java/com/softeer/caart/domain/color/entity/AvailableColor.java
  backend/src/main/java/com/softeer/caart/domain/color/entity/Color.java
  backend/src/main/java/com/softeer/caart/domain/color/entity/ColorPreview.java
  backend/src/main/java/com/softeer/caart/domain/color/exception/TrimNotFoundException.java
  backend/src/main/java/com/softeer/caart/domain/color/repository/ColorRepository.java
  backend/src/main/java/com/softeer/caart/domain/color/service/ColorService.java
  backend/src/main/java/com/softeer/caart/domain/trim/dto/response/TrimResponse.java
  backend/src/main/java/com/softeer/caart/domain/trim/entity/Trim.java
  backend/src/main/java/com/softeer/caart/domain/trim/repository/TrimRepository.java
  backend/src/main/java/com/softeer/caart/global/ResultCode.java
  backend/src/main/java/com/softeer/caart/global/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/softeer/caart/global/response/ErrorResponseDto.java
Labels: 기능개발 👨‍💻

#374 [BE] docs: 색상 목록 조회 API swagger 설명 추가
  backend/src/main/java/com/softeer/caart/domain/color/controller/ColorController.java
Labels: 수정 🛠

#369 [AOS] design: 라이프스타일 엿보기 화면 레이아웃 구현
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Answer.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Choice.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/SurveyQuestion.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/LifeStyleDetailSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/LifeStyleSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/LifestyleDetailFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/SurveyAnswerOptionsRecyclerAdapter.kt
  Android/app/src/main/res/drawable/shape_three_corner_rounded_background_r8.xml
  Android/app/src/main/res/layout/fragment_lifestyle_detail.xml
  Android/app/src/main/res/layout/layout_interview.xml
  Android/app/src/main/res/layout/layout_recomannded_trim_and_option.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/styles_textView.xml
Labels: 디자인 🖌

#368 [FE] feat: 추가 옵션 리스트 API 연동
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/NavBar.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/NavBarLower.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/NavBarUpper.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/OptionCardList.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/OptionCardListAdditionalTag.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionInfoPopup/OptionInfoPopup.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionInfoPopup/OptionInfoPopupBtn.tsx
  frontend/src/pages/vehicleEstimationPage/OptionEstimationPage.tsx
Labels: 기능개발 👨‍💻

#377 [BE] fix: 라이프스타일 & 색상 API 응답 형태 수정
  backend/src/main/java/com/softeer/caart/domain/color/dto/ColorDto.java
  backend/src/main/java/com/softeer/caart/domain/color/repository/ColorRepository.java
  backend/src/main/java/com/softeer/caart/domain/color/service/ColorService.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/controller/LifeStyleController.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/LifestyleQuestionDto.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/response/LifestyleBaseQuestionsResponse.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/entity/Question.java
Labels: 수정 🛠

#379 [AOS] feat: 결과 화면 리싸이클러 뷰 구현
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/ResultChoiceOption.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/ImageViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/ViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/ResultOptionAdapter.kt
  Android/app/src/main/res/drawable/img_my_car.png
  Android/app/src/main/res/drawable/shape_recommand_tooltip.xml
  Android/app/src/main/res/layout/fragment_estimate.xml
  Android/app/src/main/res/layout/item_result_option.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/style_view.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#375 [AOS] feat: 라이프스타일 엿보기 화면 완료 + 피드백 반영
  Android/app/build.gradle
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Cover.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/Option.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/dto/Interview.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/dto/Profile.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/state/LifestyleDetailState.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/state/RecommandationModelState.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/state/RecommendationCardState.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/data/state/RecommendationState.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/network/RecommandApiService.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/repository/RecommandRepository.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/bindingadapter/ImageViewBindingAdapter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/LifeStyleSurveyFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/LifestyleDetailFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/transformation/BlurTransformation.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/util/StringFormatter.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/LifestyleDetailViewModel.kt
  Android/app/src/main/res/drawable/shape_three_corner_rounded_background_r8.xml
  Android/app/src/main/res/layout/fragment_lifestyle_detail.xml
  Android/app/src/main/res/layout/item_result_option.xml
  Android/app/src/main/res/layout/layout_interview.xml
  Android/app/src/main/res/layout/layout_recomannded_trim_and_option.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/settings.gradle
Labels: 기능개발 👨‍💻, 디자인 🖌

#381 [AOS] feat: 견적내기 화면 레이아웃 구성
  Android/app/src/main/java/org/softeer_2nd/caArt/model/factory/DummyItemFactory.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/EstimateFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/recycleradapter/OrderDetailAdapter.kt
  Android/app/src/main/res/drawable/ic_circle_upload_68.xml
  Android/app/src/main/res/layout/fragment_car_trim_choice.xml
  Android/app/src/main/res/layout/fragment_estimate.xml
  Android/app/src/main/res/layout/item_order_detail.xml
  Android/app/src/main/res/layout/item_result_option.xml
  Android/app/src/main/res/navigation/nav_graph.xml
  Android/app/src/main/res/values/strings.xml
Labels: 기능개발 👨‍💻, 디자인 🖌

#383 [FE] feat: 옵션 선택 페이지 기본 옵션 목록 API 연동
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/navBar/NavBarUpper.tsx
  frontend/src/components/vehicleEstimationPage/optionEstimationPage/optionCardList/OptionCardListBasic.tsx
  frontend/src/pages/vehicleEstimationPage/OptionEstimationPage.tsx
Labels: 기능개발 👨‍💻

#387 [BE] feat: 카마스터 설문지 저장 API 개발
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/CarEngineSummaryResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/dto/response/WheelDriveSummaryResponse.java
  backend/src/main/java/com/softeer/caart/domain/composition/exception/BodyTypeNotFoundException.java
  backend/src/main/java/com/softeer/caart/domain/composition/exception/EngineNotFoundException.java
  backend/src/main/java/com/softeer/caart/domain/composition/exception/WheelDriveNotFoundException.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/carmaster/controller/CarMasterController.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/carmaster/dto/CreateSurveyRequest.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/carmaster/entity/CarMasterSurvey.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/carmaster/entity/RecommendedOption.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/carmaster/repository/CarMasterSurveyRepository.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/carmaster/repository/RecommendedOptionRepository.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/carmaster/service/CarMasterService.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/controller/LifeStyleController.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/dto/request/RecommendationRequest.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/entity/Answer.java
  backend/src/main/java/com/softeer/caart/domain/recommendation/lifestyle/exception/InvalidAnswerException.java
  backend/src/main/java/com/softeer/caart/domain/trim/dto/response/TrimSummaryResponse.java
  backend/src/main/java/com/softeer/caart/domain/trim/exception/TrimNotFoundException.java
  backend/src/main/java/com/softeer/caart/global/ResultCode.java
  backend/src/main/java/com/softeer/caart/global/handler/GlobalExceptionHandler.java
  backend/src/main/java/com/softeer/caart/global/response/ErrorResponseDto.java
  backend/src/test/java/com/softeer/caart/domain/recommendation/carmaster/dto/CreateSurveyRequestTest.java
  backend/src/test/java/com/softeer/caart/domain/recommendation/carmaster/service/CarMasterServiceTest.java
  backend/src/test/java/com/softeer/caart/domain/recommendation/lifestyle/entity/AnswerTest.java
Labels: 기능개발 👨‍💻, 긴급 🚨

#385 [FE] feat: 라이프스타일 질문 API 구조 변경
  frontend/src/pages/recommendPage/RecommendAgePage.tsx
  frontend/src/pages/recommendPage/RecommendDetailPage.tsx
  frontend/src/pages/recommendPage/RecommendDetailResultPage.tsx
  frontend/src/pages/recommendPage/RecommendLifeStyleResultPage.tsx
  frontend/src/pages/recommendPage/RecommendPage.tsx
  frontend/src/util/Context.tsx
Labels: 기능개발 👨‍💻, 수정 🛠

#402 [AOS] fix: 서버 변경 반영
  Android/app/src/main/java/org/softeer_2nd/caArt/model/network/OptionApiService.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/model/repository/CarOptionRepository.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/ui/fragment/CarOptionChoiceFragment.kt
  Android/app/src/main/java/org/softeer_2nd/caArt/viewmodel/CarOptionChoiceViewModel.kt
Labels: 긴급 🚨
